package app.kitsunping

import android.content.Context
import org.json.JSONObject

data class TargetPolicyRule(
    val profile: String,
    val priority: String,
    val enabled: Boolean = true
)

class TargetPolicyModelStore(context: Context) {
    private val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun loadModel(): Map<String, TargetPolicyRule> {
        val raw = prefs.getString(KEY_MODEL_JSON, "").orEmpty().trim()
        if (raw.isBlank()) return emptyMap()
        val root = runCatching { JSONObject(raw) }.getOrNull() ?: return emptyMap()
        val result = linkedMapOf<String, TargetPolicyRule>()
        val keys = root.keys()
        while (keys.hasNext()) {
            val pkg = keys.next().trim().lowercase()
            if (pkg.isBlank()) continue
            val ruleJson = root.optJSONObject(pkg) ?: continue
            val profile = normalizeProfile(ruleJson.optString("profile")) ?: continue
            val priority = normalizePriority(ruleJson.optString("priority")) ?: "medium"
            val enabled = if (ruleJson.has("enabled")) ruleJson.optBoolean("enabled", true) else true
            result[pkg] = TargetPolicyRule(profile = profile, priority = priority, enabled = enabled)
        }
        return result
    }

    fun saveModel(model: Map<String, TargetPolicyRule>) {
        val normalized = normalizeModel(model)
        val root = JSONObject()
        normalized.forEach { (pkg, rule) ->
            root.put(
                pkg,
                JSONObject()
                    .put("profile", rule.profile)
                    .put("priority", rule.priority)
                    .put("enabled", rule.enabled)
            )
        }
        prefs.edit().putString(KEY_MODEL_JSON, root.toString()).apply()
    }

    fun importFromTargetProp(targetPropRaw: String): Map<String, TargetPolicyRule> {
        if (targetPropRaw.isBlank()) return emptyMap()
        val model = linkedMapOf<String, TargetPolicyRule>()

        targetPropRaw.lineSequence().forEach { rawLine ->
            val line = rawLine.substringBefore('#').trim()
            if (line.isBlank() || !line.contains('=')) return@forEach

            val pkg = line.substringBefore('=').trim().lowercase()
            val rhs = line.substringAfter('=').trim()
            if (pkg.isBlank() || rhs.isBlank()) return@forEach

            var profile: String? = null
            var priority: String? = null
            rhs.split(',').forEach { tokenRaw ->
                val token = tokenRaw.trim().lowercase().replace(Regex("\\s*:\\s*"), ":")
                when {
                    token.startsWith("profile:") -> profile = normalizeProfile(token.substringAfter("profile:"))
                    token.startsWith("priority:") -> priority = normalizePriority(token.substringAfter("priority:"))
                    profile == null -> profile = normalizeProfile(token)
                    priority == null -> priority = normalizePriority(token)
                }
            }

            val normalizedProfile = normalizeProfile(profile) ?: return@forEach
            val normalizedPriority = normalizePriority(priority) ?: "medium"
            model[pkg] = TargetPolicyRule(normalizedProfile, normalizedPriority, enabled = true)
        }

        return model
    }

    fun renderTargetProp(model: Map<String, TargetPolicyRule>): String {
        val normalized = normalizeModel(model)
        return buildString {
            append("# target.prop generated by KitsunpingApp internal JSON model\n")
            append("# format: package=profile:<stable|speed|gaming|benchmark_gaming|benchmark_speed>, priority:<low|medium|high>\n")
            normalized.forEach { (pkg, rule) ->
                if (!rule.enabled) return@forEach
                append(pkg)
                append("=profile:")
                append(rule.profile)
                append(", priority:")
                append(rule.priority)
                append('\n')
            }
        }
    }

    fun modelToJsonText(model: Map<String, TargetPolicyRule>): String {
        val normalized = normalizeModel(model)
        val root = JSONObject()
        normalized.forEach { (pkg, rule) ->
            root.put(
                pkg,
                JSONObject()
                    .put("profile", rule.profile)
                    .put("priority", rule.priority)
                    .put("enabled", rule.enabled)
            )
        }
        return root.toString()
    }

    private fun normalizeModel(model: Map<String, TargetPolicyRule>): Map<String, TargetPolicyRule> {
        val normalized = linkedMapOf<String, TargetPolicyRule>()
        model.toSortedMap().forEach { (pkgRaw, rule) ->
            val pkg = pkgRaw.trim().lowercase()
            if (pkg.isBlank()) return@forEach
            val profile = normalizeProfile(rule.profile) ?: return@forEach
            val priority = normalizePriority(rule.priority) ?: "medium"
            normalized[pkg] = TargetPolicyRule(profile, priority, enabled = rule.enabled)
        }
        return normalized
    }

    private fun normalizeProfile(value: String?): String? {
        return when (value.orEmpty().trim().lowercase()) {
            "stable", "speed", "gaming", "benchmark_gaming", "benchmark_speed" -> value.orEmpty().trim().lowercase()
            "benchmark" -> "benchmark_gaming"
            "normal" -> "stable"
            else -> null
        }
    }

    private fun normalizePriority(value: String?): String? {
        return when (value.orEmpty().trim().lowercase()) {
            "low", "medium", "high" -> value.orEmpty().trim().lowercase()
            else -> null
        }
    }

    companion object {
        private const val PREFS_NAME = "target_policy_model"
        private const val KEY_MODEL_JSON = "target_policy_model_json"
    }
}
